use_modular_headers!
use_frameworks!
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'JABaseUIKit_Example' do
  pod 'JABaseUIKit', :path => '../'

  target 'JABaseUIKit_Tests' do
    inherit! :search_paths

  end
end
